=== hugoboos/azkaban-ldap-usermanager/src/main/resources/azkaban-groups.dtd
<!ELEMENT azkaban-groups (groups,roles)>

<!ELEMENT groups (group)+>
<!ELEMENT group EMPTY>
<!ATTLIST group
        name ID #REQUIRED
        roles IDREFS #REQUIRED>

<!ELEMENT roles (role)+>
<!ELEMENT role EMPTY>
<!ATTLIST role
        name ID #REQUIRED
        permissions CDATA #REQUIRED>

=== hugoboos/azkaban-ldap-usermanager/src/test/resources/azkaban-groups.xml
<?xml version="1.0"?>
<!DOCTYPE azkaban-groups SYSTEM "azkaban-groups.dtd">
<azkaban-groups>
    <groups>
        <group name="mathematicians" roles="administrator" />
        <group name="scientists" roles="viewer executor" />
        <group name="viewers" roles="viewer" />
    </groups>

    <roles>
        <role name="administrator" permissions="ADMIN" />
        <role name="executor" permissions="WRITE EXECUTE" />
        <role name="viewer" permissions="READ" />
    </roles>
</azkaban-groups>
